version: '3'
services:
  web:
    build: .
    ports:
    - "8082:80"
    image: renown-apparel-ui
    volumes:
      - ~/:/var/log/nginx/
  api:
    build: ../../server/
    ports:
    - "8083:8083"
    image: renown-api